### ISSUE TITLE
Randomly occuring errors cause lock poisoning

### ISSUE THREAD

**Issue by jonasbb** [nrc/rls-analysis#31]
I have seen this error happening occasionally. I don't know which action triggers it.

I don't understand the analysis part well enough to track down the error right now. I now that it causes lock poisoning. I have verified this also with logging output. Thus in the stacktrace below `lib.rs:170` actually refers to this line:
```rust
            a.as_mut().unwrap().update(per_crate, path);
```

This is the first occurring error message:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:323
stack backtrace:
   1:     0x7f37a18127fc - std::sys::imp::backtrace::tracing::imp::write::h9c41d2f69e5caabf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f37a1820cfe - std::panicking::default_hook::{{closure}}::hcc803c8663cda123
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x7f37a1820904 - std::panicking::default_hook::hd5bda4e453dfb4be
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x7f37a182119b - std::panicking::rust_panic_with_hook::hffbc74969c7b5d87
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x7f37a1821034 - std::panicking::begin_panic::hc4c5d184a1e3fb7c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x7f37a1820f59 - std::panicking::begin_panic_fmt::h34f5b320b0f94559
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x7f37a1820ee7 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x7f37a185d6ed - core::panicking::panic_fmt::h1016b85b51d1931f
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x7f37a185d624 - core::panicking::panic::h22ba9383231afe8b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:49
  10:     0x55ff24d37f0a - <core::option::Option<T>>::unwrap::hd9d52b8cd8b0c7a1
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/macros.rs:21
  11:     0x55ff24d7bc50 - <rls_analysis::AnalysisHost<L>>::reload::{{closure}}::h8e97ad97c63c09be
                        at /home/jbushart/projects/rls-analysis/src/lib.rs:170
  12:     0x55ff24cac9d5 - rls_analysis::lowering::lower::h92cb5ca8aa5d1c3d
                        at /home/jbushart/projects/rls-analysis/src/lowering.rs:41
  13:     0x55ff24d7b705 - <rls_analysis::AnalysisHost<L>>::reload::hddf9e825b96782c1
                        at /home/jbushart/projects/rls-analysis/src/lib.rs:167
  14:     0x55ff24f436db - rls::actions::ActionHandler::build::h2f0d00054fc4a046
                        at /home/jbushart/projects/rls/src/actions.rs:162
  15:     0x55ff24f44d09 - rls::actions::ActionHandler::build_current_project::h5f21aa43b6b2025a
                        at /home/jbushart/projects/rls/src/actions.rs:208
  16:     0x55ff24f44ac4 - rls::actions::ActionHandler::on_save::habda6d99f8e9f177
                        at /home/jbushart/projects/rls/src/actions.rs:199
  17:     0x55ff24f3c2e1 - rls::server::LsService::handle_message::{{closure}}::h93ecf4ee16c0f322
                        at /home/jbushart/projects/rls/src/server.rs:268
  18:     0x55ff24f22f11 - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::h620423be50906139
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:296
  19:     0x55ff24d67551 - std::panicking::try::do_call::h9c88009a22021128
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:460
  20:     0x7f37a1829fda - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  21:     0x55ff24d6549b - std::panicking::try::ha83af4b7ff28f62a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
  22:     0x55ff24d59231 - std::panic::catch_unwind::h5ad25ca49892b7dc
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
  23:     0x55ff24d62cd4 - std::thread::Builder::spawn::{{closure}}::he37a207de30ca86b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:357
  24:     0x55ff24dd8373 - <F as alloc::boxed::FnBox<A>>::call_box::h878f939d7e6d2a1e
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  25:     0x7f37a181fb54 - std::sys::imp::thread::Thread::new::thread_start::h76badbf9b0ecaf58
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  26:     0x7f37a137a6c9 - start_thread
  27:     0x7f37a02acf7e - clone
  28:                0x0 - <unknown>
```

All the following messages look like, indicating lock poisoning.

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:870
stack backtrace:
   1:     0x7f37a18127fc - std::sys::imp::backtrace::tracing::imp::write::h9c41d2f69e5caabf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f37a1820cfe - std::panicking::default_hook::{{closure}}::hcc803c8663cda123
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x7f37a1820904 - std::panicking::default_hook::hd5bda4e453dfb4be
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x7f37a182119b - std::panicking::rust_panic_with_hook::hffbc74969c7b5d87
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x7f37a1821034 - std::panicking::begin_panic::hc4c5d184a1e3fb7c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x7f37a1820f59 - std::panicking::begin_panic_fmt::h34f5b320b0f94559
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x7f37a1820ee7 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x7f37a185d6ed - core::panicking::panic_fmt::h1016b85b51d1931f
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x55ff24dbd623 - core::result::unwrap_failed::ha8ddb8433d61b621
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/macros.rs:29
  10:     0x55ff24d86dbe - <core::result::Result<T, E>>::unwrap::hdf2a853abaa0a41b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:745
  11:     0x55ff24f43701 - rls::actions::ActionHandler::build::h2f0d00054fc4a046
                        at /home/jbushart/projects/rls/src/actions.rs:162
  12:     0x55ff24f44d09 - rls::actions::ActionHandler::build_current_project::h5f21aa43b6b2025a
                        at /home/jbushart/projects/rls/src/actions.rs:208
  13:     0x55ff24f445d6 - rls::actions::ActionHandler::on_change::h657937b6f5066afb
                        at /home/jbushart/projects/rls/src/actions.rs:193
  14:     0x55ff24f3c06b - rls::server::LsService::handle_message::{{closure}}::h93ecf4ee16c0f322
                        at /home/jbushart/projects/rls/src/server.rs:264
  15:     0x55ff24f22f11 - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::h620423be50906139
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:296
  16:     0x55ff24d67551 - std::panicking::try::do_call::h9c88009a22021128
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:460
  17:     0x7f37a1829fda - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  18:     0x55ff24d6549b - std::panicking::try::ha83af4b7ff28f62a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
  19:     0x55ff24d59231 - std::panic::catch_unwind::h5ad25ca49892b7dc
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
  20:     0x55ff24d62cd4 - std::thread::Builder::spawn::{{closure}}::he37a207de30ca86b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:357
  21:     0x55ff24dd8373 - <F as alloc::boxed::FnBox<A>>::call_box::h878f939d7e6d2a1e
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  22:     0x7f37a181fb54 - std::sys::imp::thread::Thread::new::thread_start::h76badbf9b0ecaf58
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  23:     0x7f37a137a6c9 - start_thread
  24:     0x7f37a02acf7e - clone
  25:                0x0 - <unknown>
```

**Comment by nrc** [comment]
Lock poisoning is expected after a thread panics while a mutex lock is held. The fix is to fix the original panic.

Error causing line seems to be https://github.com/nrc/rls-analysis/blob/master/src/lib.rs#L169 (not sure why the line number is off by one).

At first blush it looks like we're doing a soft reload where we should be doing a hard reload, but I don't see why this doesn't in fact happen every time.

**Comment by jonasbb** [comment]
I added a debug line in line 168, therefore everything is of by one. I didn't remove it before copying the backtrace.

**Comment by nrc** [comment]
I think I have fixed this. @jonasbb could you try updating your rls-analysis and seeing if you can still repro please?

**Comment by jonasbb** [comment]
I did not experience this error this weekend. So it might be fixed. But I never had a way to reproduce it reliable, so I cannot be sure.
