### ISSUE TITLE
ICE when building with missing definition

### ISSUE THREAD

**Issue by Xanewok** [nrc/rls-analysis#68]
Tried to minimize the test case as much as I could.

src/another.rs:
```
// Empty, can also contain invalid def like pub struct MyStructDifferent {}
```

src/main.rs
```
mod another;

fn main() {
    let a = another::MyStruct {};
}
```
After executing `RUST_BACKTRACE=1 cargo rustc -- -Zsave-analysis` on the example project I get:
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:365
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:49
  10: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, D> as syntax::visit::Visitor<'l>>::visit_expr
  11: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, D> as syntax::visit::Visitor<'l>>::visit_local
  12: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, D>>::nest_tables
  13: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, D> as syntax::visit::Visitor<'l>>::visit_item
  14: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, D> as syntax::visit::Visitor<'l>>::visit_mod
  15: <rustc_save_analysis::DumpHandler<'a> as rustc_save_analysis::SaveHandler>::save
  16: <rustc_driver::RustcDefaultCalls as rustc_driver::CompilerCalls<'a>>::build_controller::{{closure}}::{{closure}}
  17: <rustc_driver::RustcDefaultCalls as rustc_driver::CompilerCalls<'a>>::build_controller::{{closure}}
  18: rustc_driver::driver::compile_input::{{closure}}
  19: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  20: rustc_driver::driver::phase_3_run_analysis_passes
  21: rustc_driver::driver::compile_input
  22: rustc_driver::run_compiler

```
whereas `cargo build` and `cargo check` gracefully fail with an appropriate error message.
Removing src/another.rs seems to prevent the ICE.
Caught this, since it also occurs in RLS.
Using fresh nightly version: `rustc 1.19.0-nightly (f062832b2 2017-06-07)`

**Comment by nrc** [comment]
No longer ICEs
